# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  one:
    docker:
      - image: cimg/ruby:2.6.8
        auth:
          username: nirmalgaurav16
          password: NimitdasV@n1
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run: echo "this is first hello"
      - run: sleep 25
  two:
    docker:
      - image: cimg/ruby:3.0.2
        auth:
          username: nirmalgaurav16
          password: NimitdasV@n1
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run: echo "this is second hello"
      - run: sleep 15

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  version: 2
  one_two:
    jobs:
      - one
      - two
